export const AirQualityTypes = {
  FETCH_AIR_QUALITY_START: "FETCH_AIR_QUALITY_START",
  FETCH_AIR_QUALITY_SUCCESS: "FETCH_AIR_QUALITY_SUCCESS",
  FETCH_AIR_QUALITY_FAILURE: "FETCH_AIR_QUALITY_FAILURE",
  FETCH_AIR_QUALITY_FORECAST_START: "FETCH_AIR_QUALITY_FORECAST_START",
  FETCH_AIR_QUALITY_FORECAST_SUCCESS: "FETCH_AIR_QUALITY_FORECAST_SUCCESS",
  FETCH_AIR_QUALITY_FORECAST_FAILURE: "FETCH_AIR_QUALITY_FORECAST_FAILURE",
};
